name: publish_helm_chart

on:
  workflow_run:
    workflows: [ "Create, Scan and Publish KAITO image" ]
    types: [ completed ]

permissions:
  id-token: write # This is required for requesting the JWT
  packages: write
  contents: write
  actions: read
  deployments: read
  pull-requests: read

jobs:
  publish-helm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.client_payload.tag }}

      - name: Publish Workspace Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts/kaito
          target_dir: charts/kaito
          linting: off
